mongo_db:
  connection_string: "mongodb+srv://HHHHHHHHHHHHHHHHHHHHHHHHH"

cloud_storage:
  credentials: "/user/app/ProyectoEndToEndPython/Project/credentials/cloudstorage.json"
  
mysql:
  host: "192.168.1.16"
  user: "root"
  pass: "root"
  port: "3310"