FROM python:3.9

RUN pip install jupyterlab
RUN pip install psycopg2-binary
RUN pip install pymongo
RUN pip install azure-storage-blob
RUN pip install sqlalchemy 
RUN pip install mysqlclient
RUN pip install cloud-sql-python-connector["pymysql"] SQLAlchemy
RUN pip install Flask
RUN pip install fastapi uvicorn[standard]
RUN pip install pip install fastapi
RUN pip install google-cloud-storage
RUN pip install google-cloud-bigquery
RUN pip install db-dtypes
RUN pip install pandasql
RUN pip install dask
RUN pip install flask_cors
RUN pip install flask_sqlalchemy


WORKDIR /user/app

